{% set version = "1.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-smoother
  version: {{ version|replace("-", "_") }}

source:
  fn: smoother_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/smoother_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/smoother/smoother_{{ version }}.tar.gz
  sha256: e8df4bc88e9d95c30c66fc10e6b1b485626828b6d28ad1a52a20168736468277

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ttr >=0.22
  run:
    - r-base
    - r-ttr >=0.22

test:
  commands:
    - $R -e "library('smoother')"  # [not win]
    - "\"%R%\" -e \"library('smoother')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=smoother
  license: GPL-2
  summary: A collection of methods for smoothing numerical data, commencing with a port of the Matlab gaussian window smoothing function. In addition, several functions typically used in smoothing of financial data are included.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
