travis:
  secure:
    BINSTAR_TOKEN: 23OoKaQUynt2n2Do1L6vGaVziDO6yX8V6djhnjyFuqgQdKTyTFteLn5t/n9dQSd4E6g4tICVT50/GXI0FmoxUEgUDSbQwDE+G0wICrm9Pe5PYf/svncrjKelskkchFPzu5jKESBvVdEWiTtYpPkqpKvxBsu7La+nH2KZA13z9sUBSavcBtMwEqhABur7eQlZ6aYqbe23cxkkncu6zzobL2aa4rNlTAI7cwVTsCmxAEKB8MEORTvx3LoBlzw3ov9cSa7FFOwcjy/jCuLbsOlJUXKAlHyKyELzrcNg3ppJe3cX4C9cm5Uiq7x3f4dWkxpn2akKGcEGYKYXaA1bCFOG3l1PLOJmIr25aPn/8ozxVrvt8ZOFgDVxVURSPs7OdYSToITXCTmnCPNYuhk5zDQQ9NtAOvJZvfL4dC9wdokWwfkD0gJ0hK2AzGlyjiG/dcLZG65O3A9zmX8dZjaC3pADq5uijoLT6FTXP5zGa0KZ96rbC4vP9uaZNgaSfaQO0SJ6vzAWE/Rxk3Ca4QbQ0rcAE+3X4efmf8TU17rKz9JL6nxpBOr6whYmT+ZIjsY6vbDpmVp08rILnNqxa6w4In8KXiNiE518M3v+S89yryuuR8uHTRnZ//m7dukFWlj6Gijq2DLf0YUllRPcZnajbkHJihIvpyXzU1vYz9lQk/Qnsj0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
