travis:
  secure:
    BINSTAR_TOKEN: JziWxZWS/OSYMnG2W+mZowNXb8pW1rXmyy8t6m3tZA4CNgN1C0p9u7YlzAca0Gv2O/yTO8EAEc/cWkNM6WXObl5iEfuLxG32XzUY2u3gxgJWpm3pRXS8+6c7nBAny4ydQlLqXis4ic6arrmaRaTaRvp5m/SBhN4ATv1wMzHR9yDNXQ5OR+NFZHuRl6AOQnQNB1M9ti5ptVV7lmc82w958p9uZf0G1VbbtkkfHd0O7JXNzuQvaU6V4DpJbja63XSHVkbFm2SVc57qklh/mxRK6xi8REP5RcZril+xEEmWhiZOlmoPUhIy4FhZNpD7hKBjaRJdVmaEZYV065yvWhyOZV8aMIcZO0qucO0Zo/fv0bD0J+gDKJtRB/BEjnrasJ7VEuY7VwnI70kbrkxaIHwxhuYwNVoLxNOf6JkTKvX5Baf5+jj5+s4piEFoSrbBpU8KI2iZyOZuuj6stgigw0fNY+/6yReJTFwGp53eKrgsBwQP8+fHUwci2Evkp9kJXtLeML4P/5Q4rYkR6EAmPUwLBIM2LCuOl0W+U3pM7nuBjqvZCCVX6t0EvjEzRgmt8+H5OwEd6a67rSGy56UgFH4OWSnkmO0TempubwQPSRI6wgzr/+oxJrT4NHLp9qROQ9LZ8GsbVoEz4xTWmKAVp/pIARbq7hv7CDhe6GoabAO65eg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
