travis:
  secure:
    BINSTAR_TOKEN: ubHTETZDMNpeRIhL3gedcVgEhDU+fzd3gIter1nIM+bNSc8BcE/qJCnf030RZjoFP4dniSgt3JsW976yLaJ5VTVrBcDcAFvNXbepugWptHWsa1jPju3xhuX0XDuK7O+JdrqWXQCm0b0XJPFycJjjoujpmr1D/94pYdlkYSL1vzjwqkHFZ7ts4qRd9JQOf+Qa+amO/i0DSrQp79Chy3liklQ/ZL+TReIj7JvgdglMvQrw8bf+cJaqi+m5GnUpHrqRJQYGkeJBYjBiFtC1FZ5uwZY6wDD2Ds2Hab9OKNAkThx9HvqsK/HEVOX0cphKdanH+5P31TVrkh4mrrJrFGhUHxLXM7PoAjnfj0gwEaDTe2XZ3QtvKp8z4zJG+tcRNV6bbxTKOtukYbGVQPGkgKSYBUT8M9Romxf3n8EhIG2XiAiuDycs5d5CQl+UiBzV4PRrgcAguD4OUC5B7jUt0gHDXtw2wmZR5FwcWGpWzfYtc1XgmTxk4wTTmpjUJKKhUycTmT4uRCMgJDMJl8BKee3Mi56RBxkE7oKd/3CqkY+B0ffoZEiZyQzf3GTgxgBi/IIoxlwG14DDlQ5So75fM0PfuNPsMqGogvIcjyYNJQF07cVFC5gseVh38B8mkCeagBPUjKsX3v3HcIjMpHpVicHk2qN928mXQ/RfjalIgW+2AOw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
